(function () {
  'use strict';
  var view = document.getElementById('view');
  var toast = document.getElementById('toast');
  var tg = window.Telegram && window.Telegram.WebApp;
  var state = { route: 'home', me: null, plans: null, archive: null, meError: null, plansError: null, archiveError: null };
  var initData = tg && tg.initData ? tg.initData : '';
  var headers = initData ? { 'X-Telegram-Init-Data': initData } : {};
  function esc(value) { return String(value == null ? '' : value).replace(/[&<>"']/g, function (c) { return ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#039;' })[c]; }); }
  function icon(name) { var paths = { home:'<path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1z"/>', crown:'<path d="m3 7 4 4 5-7 5 7 4-4-2 12H5z"/>', archive:'<path d="M4 7h16v13H4zM3 4h18v3H3zM9 11h6"/>', user:'<circle cx="12" cy="8" r="3.5"/><path d="M4.5 21c.6-4 3.1-6 7.5-6s6.9 2 7.5 6"/>', menu:'<path d="M4 7h16M4 12h16M4 17h16"/>', medical:'<path d="M12 3v6M9 6h6M6 11c0 6 6 10 6 10s6-4 6-10"/>', info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 8h.1"/>', settings:'<circle cx="12" cy="12" r="3"/><path d="M19 13.5v-3l-2-.5a7 7 0 0 0-.8-1.9l1.1-1.7-2.1-2.1-1.7 1.1A7 7 0 0 0 11.5 5L11 3H8l-.5 2a7 7 0 0 0-1.9.8L4 4.7 1.9 6.8 3 8.5a7 7 0 0 0-.8 1.9L0 11v3l2.2.5a7 7 0 0 0 .8 1.9l-1.1 1.7L4 20.2l1.7-1.1a7 7 0 0 0 1.9.8l.5 2h3l.5-2a7 7 0 0 0 1.9-.8l1.7 1.1 2.1-2.1-1.1-1.7a7 7 0 0 0 .8-1.9z'}}; return '<span class="svg-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round">' + (paths[name] || paths.info) + '</svg></span>'; }
  function api(path) { return fetch(path, { headers: headers, cache: 'no-store' }).then(function (response) { return response.json().catch(function () { return {}; }).then(function (data) { if (!response.ok) throw new Error(data.error || 'تعذر تحميل البيانات'); return data; }); }); }
  function notify(message) { if (!toast) return; toast.textContent = message; toast.classList.add('show'); clearTimeout(notify.timer); notify.timer = setTimeout(function () { toast.classList.remove('show'); }, 3200); }
  function openUrl(url) { if (!url) { notify('الرابط غير متاح حاليًا.'); return; } if (tg && tg.openTelegramLink && url.indexOf('https://t.me/') === 0) tg.openTelegramLink(url); else if (tg && tg.openLink) tg.openLink(url); else window.location.href = url; }
  function routeFromTelegram() { var params = new URLSearchParams(window.location.search || ''); var route = params.get('route'); if (!route && tg && tg.initDataUnsafe && tg.initDataUnsafe.start_param) route = tg.initDataUnsafe.start_param; var allowed = ['home','plans','archive','account','menu','settings','about','subscription']; if (allowed.indexOf(route) !== -1) state.route = route === 'subscription' ? 'plans' : route; }
  function go(route) { state.route = route; render(); if (route === 'archive' && state.archive === null && !state.archiveError) loadArchive(); }
  function nav() { document.querySelectorAll('.nav-item').forEach(function (button) { button.onclick = function () { go(button.getAttribute('data-route')); }; button.classList.toggle('active', button.getAttribute('data-route') === state.route); }); }
  function bind() { document.querySelectorAll('[data-go]').forEach(function (button) { button.onclick = function () { go(button.getAttribute('data-go')); }; }); document.querySelectorAll('[data-url]').forEach(function (button) { button.onclick = function () { openUrl(button.getAttribute('data-url')); }; }); document.querySelectorAll('[data-bot-action]').forEach(function (button) { button.onclick = function () { var links = state.me && state.me.links && state.me.links.bot || {}; openUrl(links[button.getAttribute('data-bot-action')]); }; }); document.querySelectorAll('[data-retry]').forEach(function (button) { button.onclick = function () { var target = button.getAttribute('data-retry'); if (target === 'me') { state.meError = null; loadUser(); } else if (target === 'plans') { state.plansError = null; loadPlans(); } else { state.archiveError = null; state.archive = null; loadArchive(); } }; }); document.querySelectorAll('[data-archive-id]').forEach(function (button) { button.onclick = function () { loadArchiveDetail(button.getAttribute('data-archive-id')); }; }); var back = document.querySelector('[data-action="back"]'); if (back) back.onclick = function () { if (state.route !== 'home') go('home'); else if (tg && tg.close) tg.close(); }; var more = document.querySelector('[data-action="menu"]'); if (more) more.onclick = function () { go('menu'); }; var brand = document.querySelector('.brand'); if (brand) brand.onclick = function () { go('home'); }; }
  function errorBox(message, retry) { return '<div class="empty"><strong>' + esc(message) + '</strong><button class="button secondary" data-retry="' + retry + '">إعادة المحاولة</button></div>'; }
  function avatar(user, size) { var name = user && (user.displayName || user.firstName || user.username) || '؟'; return user && user.photoUrl ? '<img class="avatar-photo" style="width:' + size + 'px;height:' + size + 'px" src="' + esc(user.photoUrl) + '" alt="صورة الحساب" />' : '<div class="avatar" style="width:' + size + 'px;height:' + size + 'px">' + esc(name.trim().charAt(0).toUpperCase()) + '</div>'; }
  function loading(label) { return '<div class="loading"><div class="spinner"></div><span>' + esc(label || 'جارٍ التحميل…') + '</span></div>'; }
  function home() { if (state.meError) return view.innerHTML = errorBox('تعذر تحميل بيانات الحساب.', 'me'); if (!state.me) return view.innerHTML = loading('جارٍ تحميل حسابك…'); var m = state.me, u = m.user || {}, p = m.progress || {}; view.innerHTML = '<section class="hero"><div class="profile">' + avatar(u, 58) + '<div><h1>مرحباً ' + esc(u.firstName || u.displayName || 'بك') + '</h1><p>' + esc(m.department || 'المجموعة الطبية') + (m.stage ? ' · المرحلة ' + esc(m.stage) : '') + '</p><div class="plan-pill">' + icon('crown') + ' ' + esc(m.plan) + '</div></div></div><div class="stats"><div class="stat"><strong>' + p.lessonsCompleted + '</strong><span>دروس مكتملة</span></div><div class="stat"><strong>' + p.attempts + '</strong><span>محاولات</span></div><div class="stat"><strong>' + p.accuracy + '%</strong><span>الدقة</span></div></div></section><div class="section-title"><h2>مساحتك التعليمية</h2><span>QMRMed</span></div><div class="grid"><div class="card clickable" data-go="archive">' + icon('archive') + '<h3>أرشيفي</h3><p>' + m.archiveCount + ' نتيجة محفوظة</p></div><div class="card clickable" data-go="plans">' + icon('crown') + '<h3>الاشتراك</h3><p>الخطة الحالية: ' + esc(m.plan) + '</p></div><div class="card clickable" data-go="account">' + icon('user') + '<h3>حسابي</h3><p>الملف والتقدم</p></div><div class="card clickable" data-go="about">' + icon('medical') + '<h3>عن QMRMed</h3><p>المنصة والمزايا</p></div></div><section class="progress-card"><div class="progress-top"><strong>تقدمك الحالي</strong><span>' + p.accuracy + '%</span></div><div class="progress-track"><div class="progress-fill" style="width:' + Math.min(100, Number(p.accuracy)) + '%"></div></div><button class="button secondary" data-go="account">عرض تفاصيل التقدم</button></section><button class="button blue" data-bot-action="home">فتح البوت</button>'; }
  function plans() { if (state.plansError) return view.innerHTML = errorBox('تعذر تحميل الخطط الحالية.', 'plans'); if (!state.plans) return view.innerHTML = loading('جارٍ تحميل الخطط…'); var current = state.me && state.me.plan; view.innerHTML = '<div class="section-label">اشتراك QMRMed</div>' + state.plans.map(function (p) { return '<section class="plan ' + (p.code === 'PLUS' ? 'featured ' : '') + (p.code === 'PRO' ? 'ultra ' : '') + (p.current || p.code === current ? 'current' : '') + '">' + (p.current || p.code === current ? '<div class="current-badge">الخطة الحالية</div>' : '') + '<div class="plan-head"><div class="plan-icon">' + icon(p.code === 'FREE' ? 'medical' : 'crown') + '</div><div><h2>' + esc(p.name) + '</h2><div class="sub">' + esc(p.subtitle) + '</div></div></div><ul>' + p.features.map(function (f) { return '<li>' + esc(f) + '</li>'; }).join('') + '</ul>' + (p.durations.length ? '<div class="duration-list">' + p.durations.map(function (d) { return '<div class="detail-box"><span>' + esc(d.label) + '</span><strong>' + d.stars + ' ⭐</strong></div>'; }).join('') + '</div><button class="button" data-bot-action="plans">الاشتراك عبر Telegram</button>' : '<div class="price-line"><span>الخطة الأساسية</span><strong>مجاني</strong></div>') + '</section>'; }).join('') + '<div class="notice">الدفع والتفعيل يتمان داخل QMRMed Bot باستخدام التدفق الحالي الآمن.</div><button class="button secondary" data-bot-action="activation">تفعيل اشتراك</button>'; }
  function account() { if (state.meError) return view.innerHTML = errorBox('تعذر تحميل بيانات الحساب.', 'me'); if (!state.me) return view.innerHTML = loading('جارٍ تحميل الحساب…'); var m = state.me, u = m.user || {}, p = m.progress || {}, s = m.subscription || {}; view.innerHTML = '<div class="section-label">حسابي</div><section class="hero"><div class="profile">' + avatar(u, 62) + '<div><h1>' + esc(u.displayName || u.firstName || 'حساب QMRMed') + '</h1><p>' + esc(u.username ? '@' + u.username : 'Telegram ID: ' + u.telegramId) + '</p><div class="plan-pill">' + icon('crown') + ' ' + esc(m.plan) + '</div></div></div></section><div class="list"><div class="row"><span>القسم</span><strong>' + esc(m.department || 'غير محدد') + '</strong></div><div class="row"><span>المرحلة</span><strong>' + esc(m.stage || 'غير محددة') + '</strong></div><div class="row"><span>حالة الاشتراك</span><strong>' + esc(s.label) + '</strong></div><div class="row"><span>تاريخ الانتهاء</span><strong>' + esc(s.endsAt ? new Date(s.endsAt).toLocaleDateString('ar-IQ') : 'لا يوجد') + '</strong></div><div class="row"><span>الأيام المتبقية</span><strong>' + s.daysRemaining + '</strong></div><div class="row"><span>الدروس المكتملة</span><strong>' + p.lessonsCompleted + '</strong></div><div class="row"><span>المحاولات</span><strong>' + p.attempts + '</strong></div><div class="row"><span>الدقة</span><strong>' + p.accuracy + '%</strong></div></div>'; }
  function archive() { if (state.archiveError) return view.innerHTML = errorBox('تعذر تحميل الأرشيف.', 'archive'); if (state.archive === null) return view.innerHTML = loading('جارٍ تحميل الأرشيف…'); var items = state.archive; view.innerHTML = '<div class="section-label">الأرشيف</div>' + (items.length ? items.map(function (item) { return '<div class="card clickable archive-item" data-archive-id="' + esc(item.id) + '">' + icon('archive') + '<div class="grow"><h3>' + esc(item.sourceName) + '</h3><p>' + esc(item.operationLabel || item.operation) + ' · ' + esc(item.createdAt ? new Date(item.createdAt).toLocaleDateString('ar-IQ') : '') + '</p></div></div>'; }).join('') : '<div class="empty">' + icon('archive') + '<br>لا توجد نتائج محفوظة بعد.</div>'); }
  function menu() { view.innerHTML = '<div class="section-label">المزيد</div><div class="list"><div class="row" data-go="about">' + icon('medical') + '<span>عن QMRMed</span></div><div class="row" data-go="settings">' + icon('settings') + '<span>الإعدادات</span></div><div class="row" data-url="https://t.me/QMRMed">' + icon('home') + '<span>القناة الرئيسية</span></div><div class="row" data-url="https://t.me/QMR7S">' + icon('info') + '<span>الأخبار</span></div><div class="row" data-url="https://t.me/QMR7S1">' + icon('info') + '<span>الدعم</span></div><div class="row" data-url="https://t.me/ID29i">' + icon('user') + '<span>المطور</span></div><div class="row" data-url="https://instagram.com/qmr7s">' + icon('info') + '<span>Instagram</span></div></div>'; }
  function settings() { view.innerHTML = '<div class="section-label">الإعدادات</div><div class="list"><div class="row"><span>الواجهة</span><strong>داكنة</strong></div><div class="row"><span>اللغة</span><strong>العربية</strong></div><div class="row" data-bot-action="home"><span>إدارة الحساب من البوت</span><strong>فتح Telegram</strong></div></div>'; }
  function about() { view.innerHTML = '<div class="section-label">عن QMRMed</div><section class="hero"><div class="profile"><div class="avatar">Q</div><div><h1>QMRMed</h1><p>منصة تعليمية لطلاب المجموعة الطبية</p></div></div></section><div class="card"><h3>منصة تعليمية متكاملة</h3><p>الدراسة والأسئلة والاختبارات والذكاء الاصطناعي والأرشيف والتقدم، وفق المزايا المتاحة فعليًا في QMRMed Bot.</p></div>'; }
  function render() { nav(); if (state.route === 'home') home(); else if (state.route === 'plans') plans(); else if (state.route === 'account') account(); else if (state.route === 'menu') menu(); else if (state.route === 'settings') settings(); else if (state.route === 'about') about(); else if (state.route === 'archive') archive(); else home(); bind(); }
  function loadUser() { api('/api/me').then(function (data) { state.me = data; state.meError = null; render(); }).catch(function (error) { state.meError = error; render(); }); }
  function loadPlans() { api('/api/plans').then(function (data) { state.plans = data; state.plansError = null; render(); }).catch(function (error) { state.plansError = error; render(); }); }
  function loadArchive() { api('/api/archive').then(function (data) { state.archive = data; state.archiveError = null; render(); }).catch(function (error) { state.archiveError = error; render(); }); }
  function loadArchiveDetail(id) { api('/api/archive/' + encodeURIComponent(id)).then(function (data) { view.innerHTML = '<div class="section-label">نتيجة الأرشيف</div><section class="article"><h3>' + esc(data.sourceName) + '</h3><p>' + esc(data.operationLabel || data.operation) + '</p><hr><div>' + esc(data.result || 'لا توجد نتيجة') + '</div></section><button class="button secondary" data-go="archive">العودة إلى الأرشيف</button>'; bind(); }).catch(function () { notify('تعذر فتح النتيجة.'); }); }
  routeFromTelegram(); if (tg) { tg.ready(); tg.expand(); if (tg.setHeaderColor) tg.setHeaderColor('#05070b'); if (tg.setBackgroundColor) tg.setBackgroundColor('#05070b'); } window.__QMRMED_RUNTIME_READY__ = true; render(); loadUser(); loadPlans(); if (state.route === 'archive') loadArchive();
}());
