import { createHash, randomUUID } from 'node:crypto';
import { Bot, Context } from 'grammy';
import { db, upsertTelegramUser } from './db.js';
import { enqueueJob } from './ai-jobs.js';

const MARKER = '⁣QMRMED_FILE_ASK:';

function requestDigest(question:string){return createHash('sha256').update(question.trim()).digest('hex').slice(0,16);}

export function registerFileAiAskBridge(bot:Bot){
  bot.callbackQuery(/^filev4:ask:([^:]+)$/,async ctx=>{const fileId=ctx.match[1];const user=await getUser(ctx);const file=await db.file.findFirst({where:{id:fileId,userId:user.id,status:'READY'},select:{id:true}});if(!file)return ctx.reply('⚠️ الملف غير جاهز للاستخدام بعد.');await ctx.answerCallbackQuery();return ctx.reply(`🔎 أرسل سؤالك عن الملف في رسالة واحدة.\n\n${MARKER}${fileId}`);});
  bot.on('message:text',async(ctx,next)=>{const replyText=ctx.message.reply_to_message&&'text' in ctx.message.reply_to_message?String(ctx.message.reply_to_message.text??''):'';const index=replyText.indexOf(MARKER);if(index<0)return next();const fileId=replyText.slice(index+MARKER.length).split(/\s|\n/)[0];if(!fileId)return ctx.reply('⚠️ تعذر تحديد الملف. افتح الملف ثم اختر «اسأل عن الملف» مرة أخرى.');const user=await getUser(ctx);const file=await db.file.findFirst({where:{id:fileId,userId:user.id,status:'READY'},select:{id:true}});if(!file)return ctx.reply('⚠️ الملف غير متاح حاليًا.');const question=ctx.message.text.trim();if(!question)return ctx.reply('⚠️ اكتب السؤال أولًا.');const baseKey=`${fileId}:ASK_FILE:${requestDigest(question)}`;let operation=await db.fileOperation.findFirst({where:{userId:user.id,requestKey:baseKey}});if(operation&&['QUEUED','RUNNING'].includes(operation.status))return ctx.reply(`⏳ السؤال قيد المعالجة بالفعل.\nالتقدم: ${operation.progress}%`);if(operation?.status==='COMPLETED'){const result=await db.fileResult.findFirst({where:{operationId:operation.id},orderBy:{version:'desc'}});if(result)return ctx.reply(`✅ الإجابة محفوظة مسبقًا.\n\n${result.content}`);}const requestKey=operation?.status==='FAILED'?`${baseKey}:retry:${Date.now()}`:baseKey;operation=await db.fileOperation.create({data:{id:randomUUID(),userId:user.id,fileId,type:'ASK_FILE',requestKey,parameters:JSON.parse(JSON.stringify({question})),status:'QUEUED',progress:0}});try{const job=await enqueueJob({userId:user.id,type:'FILE_RESULT',fileId,idempotencyKey:`result-tree:${operation.id}`,payload:{stage:'plan',kind:'result',operationId:operation.id}});await db.fileOperation.update({where:{id:operation.id},data:{jobId:job.id}});}catch(error){await db.fileOperation.update({where:{id:operation.id},data:{status:'FAILED',errorCode:'QUEUE_PUBLISH_FAILED',errorMessage:error instanceof Error?error.message:String(error),completedAt:new Date()}});return ctx.reply('⚠️ تعذر بدء معالجة السؤال الآن. يرجى المحاولة مرة أخرى.');}return ctx.reply('⏳ تم استلام السؤال. سيجري تحليله على أجزاء الملف ثم دمج الأدلة قبل إرسال الإجابة.');});
}
async function getUser(ctx:Context){if(!ctx.from)throw new Error('Missing Telegram user');return upsertTelegramUser(ctx.from);}
