import { createHash, randomUUID } from 'node:crypto';
import { mkdir, writeFile } from 'node:fs/promises';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { Bot, Context, InlineKeyboard } from 'grammy';
import type { FileOperationType } from '@prisma/client';
import { db, upsertTelegramUser } from './db.js';
import { config } from './config.js';
import { enqueueJob, republishJob } from './ai-jobs.js';
import { processFilePipelineJob } from './file-ai-pipeline-v2.js';

const execFileAsync=promisify(execFile);const MAX_FILE_BYTES=20*1024*1024;const CHUNK_SIZE=7000;const TG_LIMIT=3900;
type Page={pageNumber:number;text:string};
const OP_LABEL:Record<FileOperationType,string>={EXPLAIN:'شرح',SUMMARY:'تلخيص',QA:'أسئلة وأجوبة',MCQ:'MCQ',TRUE_FALSE:'صح/خطأ',FILL_BLANK:'أكمل الفراغ',MATCHING:'مطابقة',CASES:'حالات سريرية',VIVA:'Viva',MIND_MAP:'خريطة ذهنية',FLOWCHART:'مخطط انسيابي',COMPARISON:'مقارنة',TIMELINE:'خط زمني',DIAGNOSTIC:'خوارزمية تشخيصية',EXAM:'اختبار تجريبي',ASK_FILE:'اسأل الملف'};
function fileMenu(id:string){return new InlineKeyboard().text('📘 فهم المحتوى',`filev4:group:${id}:understand`).text('📝 الأسئلة',`filev4:group:${id}:questions`).row().text('🩺 الحالات السريرية',`filev4:group:${id}:cases`).text('🎓 الاختبارات',`filev4:group:${id}:exam`).row().text('🧠 الأدوات',`filev4:group:${id}:tools`).text('🔎 اسأل عن الملف',`filev4:ask:${id}`).row().text('📚 أرشيف النتائج',`filev4:archive:${id}`).row().text('ℹ️ حالة الملف',`filev4:status:${id}`);}
function groupMenu(id:string,group:string){const k=new InlineKeyboard();const add=(label:string,type:FileOperationType)=>k.text(label,`filev4:op:${id}:${type}`);if(group==='understand'){add('📄 تلخيص','SUMMARY');add('📘 شرح','EXPLAIN');k.row();add('📊 مقارنة','COMPARISON');add('🧭 خط زمني','TIMELINE');}if(group==='questions'){add('📝 MCQ','MCQ');add('❓ أسئلة وأجوبة','QA');k.row();add('✅ صح / خطأ','TRUE_FALSE');add('📝 أكمل الفراغ','FILL_BLANK');k.row();add('🔗 مطابقة','MATCHING');add('🎤 Viva','VIVA');}if(group==='cases'){add('🩺 حالات سريرية','CASES');add('🔬 خوارزمية تشخيصية','DIAGNOSTIC');}if(group==='exam')add('🎓 اختبار تجريبي','EXAM');if(group==='tools'){add('🧠 خريطة ذهنية','MIND_MAP');add('🔀 مخطط انسيابي','FLOWCHART');}return k.row().text('⬅️ الملف',`filev4:file:${id}`);}
function chunksForTelegram(text:string){const out:string[]=[];let rest=text.trim();while(rest.length>TG_LIMIT){let cut=Math.max(rest.lastIndexOf('\n',TG_LIMIT),rest.lastIndexOf(' ',TG_LIMIT));if(cut<TG_LIMIT*.6)cut=TG_LIMIT;out.push(rest.slice(0,cut));rest=rest.slice(cut).trimStart();}if(rest)out.push(rest);return out.length?out:[''];}
async function sendTelegram(chatId:string,text:string,keyboard?:InlineKeyboard){const parts=chunksForTelegram(text);for(let i=0;i<parts.length;i++){const body:Record<string,unknown>={chat_id:chatId,text:parts[i]};if(keyboard&&i===parts.length-1)body.reply_markup=(keyboard as any).inline_keyboard;const r=await fetch(`https://api.telegram.org/bot${config.BOT_TOKEN}/sendMessage`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});if(!r.ok)console.warn(JSON.stringify({event:'telegram_send_failed',status:r.status}));}}
function makeChunks(pages:Page[]){const out:{index:number;text:string;pageStart:number;pageEnd:number}[]=[];let current='';let start=0;let end=0;const flush=()=>{if(current.trim())out.push({index:out.length,text:current.trim(),pageStart:start,pageEnd:end});current='';start=0;end=0;};for(const page of pages){const pieces=page.text.match(new RegExp(`[\\s\\S]{1,${CHUNK_SIZE}}(?:\\n|\\s|$)`,'g'))??[page.text];for(const piece of pieces){const clean=piece.trim();if(!clean)continue;if(!current)start=page.pageNumber;if(current&&current.length+clean.length+1>CHUNK_SIZE)flush();current=current?`${current}\n${clean}`:clean;end=page.pageNumber;}}flush();return out;}
async function extractOffice(buffer:Buffer,ext:string){const dir=join(tmpdir(),`qmrmed-${randomUUID()}`);await mkdir(dir,{recursive:true});const input=join(dir,`input.${ext}`);await writeFile(input,buffer);const{stdout}=await execFileAsync('python3',['scripts/extract-office.py',input],{maxBuffer:16*1024*1024});return stdout.trim();}
async function extractPages(buffer:Buffer,mime:string,name:string):Promise<Page[]>{const ext=name.toLowerCase().split('.').pop()??'';if(mime==='application/pdf'||ext==='pdf'){const pdf=await(await import('unpdf')).getDocumentProxy(new Uint8Array(buffer));const raw=await(await import('unpdf')).extractText(pdf,{mergePages:false}) as any;const values=Array.isArray(raw.text)?raw.text:[raw.text??''];return values.map((v:any,i:number)=>({pageNumber:i+1,text:String(v??'').trim()})).filter((p:Page)=>p.text);}if(['docx','pptx'].includes(ext)||mime.includes('wordprocessingml')||mime.includes('presentationml'))return[{pageNumber:1,text:await extractOffice(buffer,ext==='pptx'?'pptx':'docx')}];if(['txt','md','csv','json'].includes(ext)||mime.startsWith('text/'))return[{pageNumber:1,text:buffer.toString('utf8').trim()}];throw new Error('UNSUPPORTED_FILE_TYPE');}
async function ingest(fileId:string){const file=await db.file.findUnique({where:{id:fileId}});if(!file)throw new Error('FILE_NOT_FOUND');const user=await db.user.findUnique({where:{id:file.userId},select:{telegramId:true}});if(!user)throw new Error('USER_NOT_FOUND');await db.file.update({where:{id:fileId},data:{status:'DOWNLOADING',errorCode:null,errorMessage:null}});const response=await fetch(`https://api.telegram.org/file/bot${config.BOT_TOKEN}/${file.storageKey}`);if(!response.ok)throw new Error(`TELEGRAM_DOWNLOAD_${response.status}`);const buffer=Buffer.from(await response.arrayBuffer());if(buffer.length>MAX_FILE_BYTES)throw new Error('FILE_TOO_LARGE');const sha256=createHash('sha256').update(buffer).digest('hex');const duplicate=await db.file.findFirst({where:{userId:file.userId,sha256,id:{not:fileId},status:{not:'DELETED'}},select:{id:true}});if(duplicate){await db.file.update({where:{id:fileId},data:{status:'CANCELLED',errorCode:'DUPLICATE_FILE',errorMessage:`Duplicate of ${duplicate.id}`}});return;}await db.file.update({where:{id:fileId},data:{status:'EXTRACTING',sha256}});const pages=await extractPages(buffer,file.mimeType,file.originalName);const chunks=makeChunks(pages);if(!chunks.length)throw new Error('NO_EXTRACTABLE_TEXT');await db.$transaction(async tx=>{await tx.filePage.deleteMany({where:{fileId}});await tx.fileChunk.deleteMany({where:{fileId}});await tx.file.update({where:{id:fileId},data:{status:'PARSING',pageCount:pages.length,extractedChars:pages.reduce((n,p)=>n+p.text.length,0),contentFingerprint:createHash('sha256').update(pages.map(p=>p.text).join('\n')).digest('hex')}});const pageIds=new Map<number,string>();for(const page of pages){const id=randomUUID();pageIds.set(page.pageNumber,id);await tx.filePage.create({data:{id,fileId,pageNumber:page.pageNumber,text:page.text,charCount:page.text.length,contentHash:createHash('sha256').update(page.text).digest('hex')}});}for(const c of chunks)await tx.fileChunk.create({data:{id:randomUUID(),fileId,pageId:pageIds.get(c.pageStart),chunkIndex:c.index,text:c.text,charCount:c.text.length,pageStart:c.pageStart,pageEnd:c.pageEnd,contentHash:createHash('sha256').update(c.text).digest('hex')}});await tx.file.update({where:{id:fileId},data:{status:'INDEXING',readyAt:new Date()}});});await db.file.update({where:{id:fileId},data:{status:'READY'}});await enqueueJob({userId:file.userId,type:'FILE_ANALYSIS',fileId,idempotencyKey:`analysis:${fileId}:tree:v1`,payload:{stage:'plan',kind:'analysis'}});await sendTelegram(user.telegramId,`📄 تم تجهيز الملف\n\n«${file.originalName}»\n\nالحالة: جاهز للاستخدام\nالصفحات: ${pages.length}\nالنص المستخرج: ${pages.reduce((n,p)=>n+p.text.length,0).toLocaleString()} حرف\n\n🧠 يجري الآن بناء خريطة معرفية للملف في الخلفية. يمكنك بدء أي عملية مباشرة.`,fileMenu(fileId));}
async function userFrom(ctx:Context){if(!ctx.from)throw new Error('Missing Telegram user');return upsertTelegramUser(ctx.from);}
async function ownedFile(ctx:Context,fileId:string){const user=await userFrom(ctx);const file=await db.file.findFirst({where:{id:fileId,userId:user.id,status:{not:'DELETED'}}});if(!file)throw new Error('FILE_NOT_FOUND');return{user,file};}
function requestDigest(parameters?:Record<string,unknown>){return createHash('sha256').update(JSON.stringify(parameters??{})).digest('hex').slice(0,16);}
async function queue(ctx:Context,fileId:string,type:FileOperationType,parameters?:Record<string,unknown>){const{user,file}=await ownedFile(ctx,fileId);let ready=file;if(ready.status==='FAILED'&&(ready.pageCount??0)>0&&(ready.extractedChars??0)>0&&await db.fileChunk.count({where:{fileId}})>0)ready=await db.file.update({where:{id:fileId},data:{status:'READY',errorCode:null,errorMessage:null}});if(ready.status!=='READY')return ctx.reply('⏳ الملف قيد التجهيز. ستتمكن من استخدامه فور اكتمال الاستخراج.');const baseKey=`${fileId}:${type}:${requestDigest(parameters)}`;let operation=await db.fileOperation.findFirst({where:{userId:user.id,requestKey:baseKey}});if(operation&&['QUEUED','RUNNING'].includes(operation.status)){if(operation.status==='QUEUED'&&operation.jobId)await republishJob(operation.jobId).catch(()=>undefined);return ctx.reply(`⏳ العملية «${OP_LABEL[type]}» قيد المعالجة بالفعل.\nالحالة: ${operation.status}\nالتقدم: ${operation.progress}%`,{reply_markup:new InlineKeyboard().text('ℹ️ حالة العملية',`filev4:opstatus:${operation.id}`).row().text('⬅️ الملف',`filev4:file:${fileId}`)});}if(operation?.status==='COMPLETED'){const result=await db.fileResult.findFirst({where:{operationId:operation.id},orderBy:{version:'desc'}});if(result)return ctx.reply(`✅ «${OP_LABEL[type]}» مكتملة مسبقًا.\n\n${result.content}`,{reply_markup:new InlineKeyboard().text('📚 الأرشيف',`filev4:archive:${fileId}`).row().text('⬅️ الملف',`filev4:file:${fileId}`)});}const requestKey=operation?.status==='FAILED'?`${baseKey}:retry:${Date.now()}`:baseKey;operation=await db.fileOperation.create({data:{id:randomUUID(),userId:user.id,fileId,type,requestKey,parameters:parameters?JSON.parse(JSON.stringify(parameters)):undefined,status:'QUEUED',progress:0}});try{const job=await enqueueJob({userId:user.id,type:'FILE_RESULT',fileId,idempotencyKey:`result-tree:${operation.id}`,payload:{stage:'plan',kind:'result',operationId:operation.id}});await db.fileOperation.update({where:{id:operation.id},data:{jobId:job.id}});}catch(error){await db.fileOperation.update({where:{id:operation.id},data:{status:'FAILED',errorCode:'QUEUE_PUBLISH_FAILED',errorMessage:error instanceof Error?error.message:String(error),completedAt:new Date()}});return ctx.reply('⚠️ تعذر بدء المعالجة الآن. لم يتم فقدان الملف، ويمكن إعادة المحاولة.');}return ctx.reply(`⏳ بدأت «${OP_LABEL[type]}»\n\nالمرحلة الحالية: تقسيم وتحليل متوازٍ\nالحالة: QUEUED\n\nسيتم تجميع النتائج والتحقق منها قبل إرسال الإجابة.`,{reply_markup:new InlineKeyboard().text('ℹ️ حالة العملية',`filev4:opstatus:${operation.id}`).row().text('⬅️ الملف',`filev4:file:${fileId}`)});}
export async function processFileJob(job:{id:string;type:string;fileId:string;payload:unknown}){if(job.type==='FILE_INGESTION')return ingest(job.fileId);return processFilePipelineJob(job);}
export function registerFileAiV4Handlers(bot:Bot){
  bot.on('message:document',async ctx=>{const doc=ctx.message.document;if(!doc.file_size||doc.file_size>MAX_FILE_BYTES)return ctx.reply('⚠️ حجم الملف يتجاوز الحد المدعوم وهو 20 MB.');const user=await userFrom(ctx);const existing=await db.file.findFirst({where:{userId:user.id,storageKey:doc.file_id,status:{not:'DELETED'}}});if(existing)return ctx.reply('📄 هذا الملف موجود مسبقًا.',{reply_markup:fileMenu(existing.id)});const file=await db.file.create({data:{id:randomUUID(),userId:user.id,originalName:(doc.file_name??'qmrmed-file').slice(0,500),mimeType:doc.mime_type??'application/octet-stream',sizeBytes:BigInt(doc.file_size),sha256:createHash('sha256').update(`telegram:${doc.file_id}`).digest('hex'),storageKey:doc.file_id,status:'RECEIVED'}});try{await enqueueJob({userId:user.id,type:'FILE_INGESTION',fileId:file.id,idempotencyKey:`ingest:${file.id}`,payload:{fileId:file.id}});}catch(error){await db.file.update({where:{id:file.id},data:{status:'FAILED',errorCode:'QUEUE_PUBLISH_FAILED',errorMessage:error instanceof Error?error.message:String(error)}});return ctx.reply('⚠️ تعذر بدء معالجة الملف. يرجى إعادة الإرسال.');}return ctx.reply(`📄 تم استلام الملف\n\n«${file.originalName}»\nالحالة: قيد التجهيز\nالمرحلة: الاستلام → الاستخراج → الفهرسة`,{reply_markup:new InlineKeyboard().text('🔄 تحديث الحالة',`filev4:status:${file.id}`)});});
  bot.callbackQuery(/^filev4:group:([^:]+):([^:]+)$/,async ctx=>{await ctx.answerCallbackQuery();const{file}=await ownedFile(ctx,ctx.match[1]);return ctx.editMessageText(`📄 ${file.originalName}\n\nاختر القسم المطلوب:`,{reply_markup:groupMenu(file.id,ctx.match[2])});});
  bot.callbackQuery(/^filev4:file:([^:]+)$/,async ctx=>{await ctx.answerCallbackQuery();const{file}=await ownedFile(ctx,ctx.match[1]);return ctx.editMessageText(`📄 ${file.originalName}\n\nاختر العملية المطلوبة:`,{reply_markup:fileMenu(file.id)});});
  bot.callbackQuery(/^filev4:op:([^:]+):([A-Z_]+)$/,async ctx=>{await ctx.answerCallbackQuery('تم استلام الطلب');return queue(ctx,ctx.match[1],ctx.match[2] as FileOperationType);});
  bot.callbackQuery(/^filev4:status:([^:]+)$/,async ctx=>{await ctx.answerCallbackQuery();const{file}=await ownedFile(ctx,ctx.match[1]);let current=file;if(current.status==='FAILED'&&(current.pageCount??0)>0&&(current.extractedChars??0)>0&&await db.fileChunk.count({where:{fileId:file.id}})>0)current=await db.file.update({where:{id:file.id},data:{status:'READY',errorCode:null,errorMessage:null}});const latest=await db.aIJob.findFirst({where:{fileId:file.id,type:'FILE_ANALYSIS'},orderBy:{createdAt:'desc'},select:{status:true,progress:true,stage:true}});const user=await userFrom(ctx);const ops=await db.fileOperation.findFirst({where:{fileId:file.id,userId:user.id,status:{in:['QUEUED','RUNNING']}},orderBy:{createdAt:'desc'},select:{type:true,status:true,progress:true}});const details=current.errorMessage?`\nالخطأ: ${current.errorMessage.slice(0,300)}`:'';return ctx.editMessageText(`📄 ${current.originalName}\n\nالحالة: ${current.status==='READY'?'جاهز للاستخدام':current.status}\nالصفحات: ${current.pageCount??'-'}\nالنص المستخرج: ${current.extractedChars.toLocaleString()} حرف${latest?`\n🧠 الخريطة المعرفية: ${latest.status==='COMPLETED'?'مكتملة':latest.stage??latest.status}`:''}${ops?`\n⏳ العملية الحالية: ${OP_LABEL[ops.type]} — ${ops.progress}%`:''}${details}`,{reply_markup:new InlineKeyboard().text('🔄 تحديث',`filev4:status:${file.id}`).row().text('⬅️ الملف',`filev4:file:${file.id}`)});});
  bot.callbackQuery(/^filev4:opstatus:([^:]+)$/,async ctx=>{await ctx.answerCallbackQuery();const user=await userFrom(ctx);const op=await db.fileOperation.findFirst({where:{id:ctx.match[1],userId:user.id},include:{file:true}});if(!op)return ctx.editMessageText('❌ العملية غير موجودة.');if(op.status==='QUEUED'&&op.jobId)await republishJob(op.jobId).catch(()=>undefined);return ctx.editMessageText(`🧠 ${OP_LABEL[op.type]}\n\nالحالة: ${op.status}\nالتقدم: ${op.progress}%\nالملف: ${op.file.originalName}`,{reply_markup:new InlineKeyboard().text('🔄 تحديث',`filev4:opstatus:${op.id}`).row().text('⬅️ الملف',`filev4:file:${op.fileId}`)});});
  bot.callbackQuery(/^filev4:archive:([^:]+)$/,async ctx=>{await ctx.answerCallbackQuery();const{user}=await ownedFile(ctx,ctx.match[1]);const rows=await db.fileResult.findMany({where:{operation:{userId:user.id,fileId:ctx.match[1]}},orderBy:{createdAt:'desc'},take:10,select:{title:true,createdAt:true,operationId:true}});const text=rows.length?rows.map((r,i)=>`${i+1}. ${r.title} — ${r.createdAt.toLocaleString('ar-IQ')}`).join('\n'):'لا توجد نتائج محفوظة بعد.';return ctx.editMessageText(`📚 أرشيف الملف\n\n${text}`,{reply_markup:new InlineKeyboard().text('⬅️ الملف',`filev4:file:${ctx.match[1]}`)});});
}
